### ISSUE TITLE
Cursor behavior

### ISSUE THREAD

**Issue by firgaty** [Peaupote/advance-war#4]
Cursor leaves the map when a vertical and horizontal arrow key are pressed repetively fast enough.
The Cursor also leaves the map and is not bounded to it.

**Comment by Peaupote** [comment]
The bug has been fixed !

Le bug venait du fait que lorsqu'une touche était pressée, on ne passais pas immédiatement dans le mode `listening`. Si bien que quand on pressais deux touches en même temps il y avait un décalage d'indice entre deux appels de la fonction update du controller.
